########### Todos ###########

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0OWM2YjUyMS1iZDljLTQ0YmItYWM0NC02NTI0NDNkODk5ZmIiLCJpYXQiOjE3MzIxMTQzNzEsImV4cCI6MTczMjcxOTE3MX0.StVTw9p7qhUb_VQgIOR_bNWyH0U8ozTT58uCN1SyePQ


### Get All Todos
GET http://localhost:5000/api/v1/todos
Authorization: Bearer {{refreshToken}}


### Create Todo
POST http://localhost:5000/api/v1/todos
Authorization: Bearer {{refreshToken}}
Content-Type: application/json

{
    "title": "New Todo",
    "description": "Finish the project and submit it on time."
}

### Get Todo By Id
@todoId = 8d9af10a-3e52-4a92-9c12-f6c1a676474b

GET http://localhost:5000/api/v1/todos/{{todoId}}
Authorization: Bearer {{refreshToken}}


### Update Todo
PUT http://localhost:5000/api/v1/todos/{{todoId}}
Authorization: Bearer {{refreshToken}}
Content-Type: application/json

{
    "title": "Updated Complete project",
    "description": "Finish the project and submit it by next week.",
    "status": "IN_PROGRESS"
}


### Delete Todo
DELETE http://localhost:5000/api/v1/todos/{{todoId}}
Authorization: Bearer {{refreshToken}}